language: node_js

node_js:
- '10'

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script: npm run lint && npm test

notifications:
  email: false

cache:
  directories:
    - node_modules

after_success:
- npm run codecov

addons:
  chrome: stable

before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

dist: trusty